### PR TITLE
Port custom airframe configs / mixers to public fork

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This PR ports ethz asl fixedwing team's custom airframe configs and mixers to the PX4 fork

**Describe your solution**
There has been some fixes that needed to be done when bring the airframe configs more up to date.
- The shibang has changed from `! nsh` to `/bin/sh`
- The prefix for aerial vehicles `2200` was taken upstream, so I just bumped the numbering up to `22000` (e.g. https://github.com/ethz-asl/fw_px4/blob/master/ROMFS/px4fmu_common/init.d/2200_ASL_EasyGlider)
- Upper case file names have been lowered to small cases
- The rcS script is no longer under `/etc/init.d` but under `. ${R}etc/init.d/`

**Test data / coverage**
This has **NOT** been tested, but will be tested with the easyglider as we are building it up with the pixhawk4

sensesoar, techpod are added just as place holders for the airframe config numbers

**Additional context**
- This was included in the TODO porting lists in https://docs.google.com/document/d/18kFFqfUwXZ-8EeRawj5QPjD-2_Yoq_ie0H3g60dGzNU/edit?usp=sharing
- The airframe numbering is a bit random, and we need to be careful if there are any duplicates included from upstream. (If there are two airframe configs with the same number the rcS will start both of them screwing up the system really bad)

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
fmuv2 has run out of flash

**Comment by tstastny** [comment]
>     * The airframe numbering is a bit random, and we need to be careful if there are any duplicates included from upstream

I think it is ok to renumber our platforms - probably now is the the right time since we are updating everything anyway. Should we push our platforms upstream then such that we don't need to change them later? What is your opinion on this @Jaeyoung-Lim 

> fmuv2 has run out of flash

This seems to be a prevalent issue upstream as well, right? What is the current way ppl are handling this? If we assume we don't do v2 anymore, is there a way to bypass this? Or must things always still be backwards compatible?

**Comment by Jaeyoung-Lim** [comment]
> I think it is ok to renumber our platforms - probably now is the the right time since we are updating everything anyway. Should we push our platforms upstream then such that we don't need to change them later? What is your opinion on this @Jaeyoung-Lim

I think that would certainly fix the problem, but not sure if the vehicles where people do not have access (sensesoar2, techpod) will be accepted upstream. I think having custom airframe configs will always be needed on ourside, but not sure how this can be fixed. (Probably a reserved number on upstream for custom vehicles?)

> > fmuv2 has run out of flash
> 
> This seems to be a prevalent issue upstream as well, right? What is the current way ppl are handling this? If we assume we don't do v2 anymore, is there a way to bypass this? Or must things always still be backwards compatible?

I have masked the fmuv2 from our vehicles so it doesn't get built. (as well as the crazyflie vehicle)

**Comment by tstastny** [comment]
> I think that would certainly fix the problem, but not sure if the vehicles where people do not have access (sensesoar2, techpod) will be accepted upstream. I think having custom airframe configs will always be needed on ourside, but not sure how this can be fixed. (Probably a reserved number on upstream for custom vehicles?)

Ok - so for now we just take a number that isnt used locally. Has this been discussed upstream about reserving a custom vehicle config number? Should we initiate this conversation? (I honestly haven't thought too much into it.. so maybe there is also a reason not to do this)

> I have masked the fmuv2 from our vehicles so it doesn't get built. (as well as the crazyflie vehicle)

Ok.

**Comment by Jaeyoung-Lim** [comment]
@tstastny Since we have the dev call today, I will bring it up!

**Comment by Jaeyoung-Lim** [comment]
@tstastny Discussed in today's dev call and we decided to reserve some IDs for downstream models. PR in https://github.com/PX4/PX4-Autopilot/pull/16815

**Review by tstastny — APPROVED** [review]

**Pull request merged**
